### ISSUE TITLE
Can't get ScrollPanel to work

### ISSUE THREAD

**Issue by ken92** [nifty-gui/nifty-gui#417]
Hello!  I'm new to Nifty GUI, so I think I'm just missing something simple.  The short of it is that I can't get my ScrollPanel to work!  It displays and I see the scrollbar, but clicking on it does not scroll.

Here is the XML code I have:

``` xml
<screen id="start">
  <layer childLayout="vertical">
    <panel childLayout="vertical" backgroundColor="#f008" padding="20px" height="75%" width="100%">
      <control id="main_text_scrollbar" name="scrollPanel" horizontal="false" height="100%">
        <panel id="main_text_panel" childLayout="vertical" backgroundColor="#f008" width="100%" height="100%">
          <text id="main_text" wrap="true" font="aurulent-sans-16.fnt" color="#000000"
            text="Hello
                  There are a bunch of new line symbols here
                  World!" />
          </panel>
        </control>
       </panel>

     Other things are in here
  </layer>
</screen>
```

Currently, there is no Java code to go with this.  I tried using the code from the scroll example in the Nifty.zip, but the class used is deprecated and I was unable to find another working example.

I'd really appreciate any help I can get!  Thanks!

Edit: Sorry for the weird formatting and lack of brackets; most of my code became invisible when I posted it.

**Comment by relu91** [comment]
I've corrected the code syntax :smile: . I think that problem is main_text_panel. You should set the height and width of that element in px not as 100% otherwise the scroll panel can't work.

**Comment by ken92** [comment]
Thank you for fixing my formatting!

I tried setting main_text_panel's width and height to no avail; the scrollbar looks like it should be scrollable, but it still does nothing when I click on it.  This is a step in the right direction, though!

**Comment by ken92** [comment]
Last night I tested this on one laptop with an older version of Eclipse, but now that I am trying it on a different laptop with a newer version of Eclipse, the scrolling is suddenly working.  I don't know what changed, but I can now scroll!  Unfortunately, I still cannot see the "World!" at the bottom of my string.  I intend to use this text area to display all manner of texts as events happen (I'm making a GUI for a text-based game), so I want to be sure that no matter how long the text is, the user will be able to read it.  Do you have any suggestions on how to make sure I can always scroll to the very bottom?

**Comment by ken92** [comment]
For anyone who might be looking at this later, my XML currently looks like this:

``` xml
    <screen id="start">
        <layer childLayout="vertical">
            <panel childLayout="vertical" backgroundColor="#f008" padding="20px" height="75%" width="100%">
                <control id="main_text_scrollbar" name="scrollPanel" horizontal="false" height="100%">
                <!-- <control id="main_text_scrollbar" name="scrollPanel" horizontal="false" height="225px">-->
                    <panel id="main_text_panel" childLayout="vertical" backgroundColor="#f008" width="700px" height="1000px">
                        <text id="main_text" wrap="true" font="aurulent-sans-16.fnt" color="#000000"
                            text="Hello &#xA;&#xA;&#xA;&#xA;&#xA;&#xA;&#xA;&#xA;&#xA;&#xA;&#xA;&#xA;&#xA;&#xA;&#xA;
                            &#xA;&#xA;&#xA;&#xA;&#xA;&#xA;&#xA;&#xA;&#xA;&#xA;&#xA;&#xA;&#xA;&#xA;&#xA;&#xA;&#xA;&#xA;&#xA;&#xA;&#xA;&#xA;&#xA;
                            &#xA;&#xA;&#xA;&#xA;&#xA;&#xA;&#xA;&#xA;&#xA;&#xA;&#xA;&#xA;&#xA;&#xA;&#xA;&#xA;&#xA;&#xA;&#xA;&#xA;&#xA;&#xA;&#xA;
                            &#xA;&#xA;&#xA;&#xA;&#xA;&#xA;&#xA;&#xA;&#xA;&#xA;&#xA;&#xA;&#xA;&#xA;&#xA;&#xA;&#xA;&#xA;&#xA;&#xA;&#xA;&#xA;&#xA;
                            World!" />
                    </panel>
                </control>
            </panel>

            <!-- Other things -->
        </layer>
    </screen>
```

**Comment by ken92** [comment]
I was able to hack together an _extremely_ messy workaround until I find a more elegant solution by adding this to my main class:

```
    Element mainTextPanel = screen.findElementById("main_text_panel");
    Element mainTextPanelContainer = screen.findElementById("main_text_panel_container");
    int mainTextPanelContainerTopPadding = mainTextPanelContainer.getPaddingTop().getValueAsInt(1)*4;
    System.out.println("mainTextPanelContainerTopPadding: "+mainTextPanelContainerTopPadding);

    ScrollPanel scrollPanel = screen.findNiftyControl("main_text_scrollbar", ScrollPanel.class);
    System.out.println("mainTextPanelContainer.getHeight(): "+mainTextPanelContainer.getHeight());
    scrollPanel.setHeight(new SizeValue((mainTextPanelContainer.getHeight()+scrollPanel.getHeight())+"px"));
    mainTextPanel.setConstraintHeight(new SizeValue((mainTextPanelContainer.getHeight()+scrollPanel.getHeight()*2+mainTextPanelContainerTopPadding)+"px"));
    mainTextPanel.setConstraintWidth(new SizeValue((mainTextPanelContainer.getWidth())+"px"));
```

The numbers I'm multiplying the values by were chosen arbitrarily.  The scrollbar can now leak off the end of its container if I drag it.  Also, the arrow buttons for the scrollbar still don't work.  Do you have any ideas?  I really appreciate your help!

**Comment by relu91** [comment]
Sorry could you make an SSCCE [here](https://github.com/nifty-gui/nifty-gui-issues)? This way other and I could easily look at your code and see if we can solve this issue :smile: . Thank you!

**Comment by ken92** [comment]
Wow, that looks neat!  How do I push to this repo?  Should I make a pull request and push it like that?  I've never pushed to someone else's repo on here before.

**Comment by relu91** [comment]
I think that a pull request should work just fine, Isn't it @void256 ?

**Comment by bgroenks96** [comment]
@relu91 Yes a PR will do it. Any members of the nifty team can merge it once it has been verified.

**Comment by ken92** [comment]
I created a pull request!  The files for LWJGL 2.9.3 are not included with the merge, but I can easily add them upon request.

**Comment by ken92** [comment]
I was able to get my code to work!  I believe that there may be a better way to go about doing this, but this is the code I ended up with:

```
    private void refreshMainTextPanelSize() {
        Screen screen = nifty.getCurrentScreen();
        Element mainTextPanel = screen.findElementById("main_text_panel");
        Element mainTextPanelContainer = screen.findElementById("main_text_panel_container");
        int mainTextPanelContainerTopPadding = mainTextPanelContainer.getPaddingTop().getValueAsInt(1);
        System.out.println("mainTextPanelContainerTopPadding: "+mainTextPanelContainerTopPadding);

        ScrollPanel scrollPanel = screen.findNiftyControl("main_text_scrollbar", ScrollPanel.class);
        System.out.println("mainTextPanelContainer.getHeight(): "+mainTextPanelContainer.getHeight());
        mainTextPanel.setConstraintHeight(new SizeValue((mainTextPanelContainer.getHeight()+scrollPanel.getHeight()+mainTextPanelContainerTopPadding)+"px"));
        mainTextPanel.setConstraintWidth(new SizeValue((mainTextPanelContainer.getWidth())+"px"));

        int newTextPanelHeight = mainTextPanel.getConstraintHeight().getValueAsInt(1);
        System.out.println("newTextPanelHeight: "+newTextPanelHeight);
        scrollPanel.setHeight(new SizeValue(newTextPanelHeight+"px"));
    }
```

**Comment by ken92** [comment]
I lied!  I added more text to my test string and the end was cut off.  My temporary workaround:

```
    private void refreshMainTextPanelSize() {
        Screen screen = nifty.getCurrentScreen();
        Element mainTextPanel = screen.findElementById("main_text_panel");
        Element mainTextPanelContainer = screen.findElementById("main_text_panel_container");
        int mainTextPanelContainerTopPadding = mainTextPanelContainer.getPaddingTop().getValueAsInt(1)*4;
        System.out.println("mainTextPanelContainerTopPadding: "+mainTextPanelContainerTopPadding);

        ScrollPanel scrollPanel = screen.findNiftyControl("main_text_scrollbar", ScrollPanel.class);
        System.out.println("mainTextPanelContainer.getHeight(): "+mainTextPanelContainer.getHeight());
        mainTextPanel.setConstraintHeight(new SizeValue((mainTextPanelContainer.getHeight()+scrollPanel.getHeight()*2+mainTextPanelContainerTopPadding)+"px"));
        mainTextPanel.setConstraintWidth(new SizeValue((mainTextPanelContainer.getWidth())+"px"));

        int newTextPanelHeight = mainTextPanel.getConstraintHeight().getValueAsInt(1);
        System.out.println("newTextPanelHeight: "+newTextPanelHeight);
        scrollPanel.setHeight(new SizeValue(newTextPanelHeight+"px"));
    }
```
